services:
  - type: web
    name: backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"


    - type: static
    name: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: frontend/dist

